version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - /var/www/storage
      - /var/www/bootstrap/cache

    environment:
      APP_ENV: local
      APP_DEBUG: false
      APP_URL: http://localhost:8000
    command: php artisan serve --host=0.0.0.0 --port=8000
